#cloud-config
package_update: true
package_upgrade: true
packages:
  - apache2
  - fail2ban
  - ruby-full
  - build-essential
  - zlib1g-dev
runcmd:
  - ["wget","https://raw.githubusercontent.com/acenet-arc/cloud_from_a_to_z/master/cloud-init-files/passphrase_generator.py"]
  - ["wget","https://raw.githubusercontent.com/acenet-arc/cloud_from_a_to_z/master/cloud-init-files/setup_jekyll_and_guest_accounts.py"]
  - ["python3","./setup_jekyll_and_guest_accounts.py","1"]
